### ISSUE TITLE
Is there some way to find out the match time that is shown on Sbobet itself?

### ISSUE THREAD

**Issue by 1byari** [BettingApi/js-rest-client#2]
I mean, you can just subtract the time date_start and actual_at, but this does not guarantee the required accuracy. Also, I tried to make a request to Sbobet directly, but it always redirects to the main page

**Comment by zvs001** [comment]
@1byari Added support.
You can test already.

```typescript
{
    half_index?: number
    minute?: number
}
```

**Comment by 1byari** [comment]
> @1byari Added support.
> You can test already.
> 
> ```ts
> {
>     half_index?: number
>     minute?: number
> }
> ```

Wow dude thanks a lot. Your API is very cool. I really appreciate it🙏

**Comment by zvs001** [comment]
Thank you 😊
