### ISSUE TITLE
How to get info of a finished match?

### ISSUE THREAD

**Issue by kieuconghau** [BettingApi/js-rest-client#4]
I want to get the result (scores) after the match is finished, but maybe the API does not support this. I have tried to use this API `https://api.betting-api.com/1xbet/football/match/:id`, and it has not worked with the finished matches.

**Comment by zvs001** [comment]
It is not supported in the moment. 
You can store history on your side.

**Comment by kevin4dhd** [comment]
Any solution?

**Comment by kevin4dhd** [comment]
I need to know the result of the bet
